BEGIN TRANSACTION;

ALTER TABLE transactions ADD COLUMN reimbursable INTEGER DEFAULT 0;
ALTER TABLE transactions ADD COLUMN reimbursed INTEGER DEFAULT 0;
ALTER TABLE transactions ADD COLUMN reimbursed_by TEXT DEFAULT NULL;

COMMIT;
